# Generated by Django 5.0.6 on 2024-10-10 08:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('meniu', models.FileField(upload_to='pdf-menus')),
                ('servicii_catering', multiselectfield.db.fields.MultiSelectField(choices=[('Bar si bauturi', 'Bar si bauturi'), ('Bufet', 'Bufet'), ('CandyBar', 'CandyBar'), ('Chef', 'Chef'), ('Degustare', 'Degustare'), ('Livrare', 'Livrare'), ('Aranjare', 'Aranjare'), ('Personal Servire', 'Personal Servire'), ('Fruit Bar', 'Fruit Bar')], default='', max_length=88)),
            ],
            bases=('MainApp.clientdetails',),
        ),
        migrations.CreateModel(
            name='Cofetarie',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('meniu', models.FileField(upload_to='pdf-menus')),
                ('servicii_cofetarie', multiselectfield.db.fields.MultiSelectField(choices=[('Candy Bar', 'Candy Bar'), ('Torturi personalizate', 'Torturi personalizate'), ('Livrare', 'Livrare'), ('Machete', 'Machete'), ('Fantana Ciocolata', 'Fantana Ciocolata'), ('Fruit Bar', 'Fruit Bar')], default='', max_length=75)),
            ],
            bases=('MainApp.clientdetails',),
        ),
    ]
