# Generated by Django 5.0.6 on 2024-10-10 08:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('muscial_styles_field', multiselectfield.db.fields.MultiSelectField(choices=[('Clasic', 'Clasic'), ('Disco', 'Disco'), ('Folclor', 'Folclor'), ('Hip-Hop', 'Hip=Hop'), ('Instrumental', 'Instrumental'), ('Jazz', 'Jazz'), ('Latino', 'Latino'), ('Pop', 'Pop'), ('Rock', 'Rock'), ('Manele', 'Manele'), ('Lautareasca', 'Lautareasca'), ('Retro', 'Retro'), ('Mix', 'Mix'), ('Live', 'Live')], default='', max_length=96)),
                ('tip', models.CharField(choices=[('Formatie', 'Formatie'), ('DJ', 'DJ')], default='')),
            ],
            bases=('MainApp.clientdetails',),
        ),
    ]
