# Generated by Django 5.0.6 on 2024-10-10 08:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_webpage', models.URLField()),
                ('client_facebook_page', models.URLField()),
                ('client_instagram_page', models.URLField()),
                ('client_tiktok_page', models.URLField()),
                ('client_adress', models.CharField(max_length=250)),
                ('client_county', models.CharField(choices=[('Bucuresti', 'Bucuresti'), ('Cluj', 'Cluj'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta'), ('Timis', 'Timis'), ('Brasov', 'Brasov'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Bihor', 'Bihor'), ('Prahova', 'Prahova'), ('Braila', 'Braila'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Sibiu', 'Sibiu'), ('Mures', 'Mures'), ('Maramures', 'Maramures'), ('Buzau', 'Buzau'), ('Valcea', 'Valcea'), ('Satu Mare', 'Satu Mare'), ('Botosani', 'Botosani'), ('Suceava', 'Suceava'), ('Caras-Severin', 'Caras-Severin'), ('Mehedinti', 'Mehedinti'), ('Neamt', 'Neamt'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Gorj', 'Gorj'), ('Dambovita', 'Dambovita'), ('Vrancea', 'Vrancea'), ('Tulcea', 'Tulcea'), ('Alba', 'Alba'), ('Olt', 'Olt'), ('Vaslui', 'Vaslui'), ('Calarasi', 'Calarasi'), ('Giurgiu', 'Giurgiu'), ('Ilfov', 'Ilfov'), ('Hunedoara', 'Hunedoara'), ('Salaj', 'Salaj'), ('Covasna', 'Covasna'), ('Harghita', 'Harghita'), ('Ialomita', 'Ialomita'), ('Teleorman', 'Teleorman')], default='Bucuresti')),
                ('client_city', models.CharField(choices=[('Bucuresti', 'Bucuresti')], default='Bucuresti', max_length=255)),
                ('client_description', models.TextField()),
                ('client_events', multiselectfield.db.fields.MultiSelectField(choices=[('EVENIMENTE FESTIVE', 'Evenimente Festive'), ('EVENIMENTE CORPORATE', 'Evenimente Corporate'), ('PETRECERI PRIVATE', 'Petreceri Private')], default='', max_length=57)),
            ],
        ),
    ]
