# Generated by Django 5.0.6 on 2024-06-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_platformclient_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformCLient',
        ),
    ]
