# Generated by Django 5.0.6 on 2024-06-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BallRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone_number', models.CharField(max_length=10)),
                ('minimum_guests_number', models.ImageField(upload_to='')),
                ('maximum_guests_number', models.IntegerField()),
                ('type_of_events', models.CharField(choices=[('NUNTA', 'Nunta'), ('BOTEZ', 'Botez'), ('CORPORATE', 'Corporate'), ('ALTELE', 'Altele')])),
                ('location_facilities', models.CharField(choices=[('Aer Conditionat', 'Aer Conditionat'), ('Sistem de sonorizare', 'Sistem de sonorizare'), ('Lumini arhitecturale', 'Lumini arhitecturale'), ('Iluminat profesional', 'Iluminat profesional'), ('Ring de dans', 'Ring de dans'), ('Scenă pentru formație/muzicieni', 'Scenă pentru formație/muzicieni'), ('Decoratiuni incluse', 'Decoratiuni incluse'), ('Baie Separata', 'Baie Separata'), ('Prezidiu', 'Prezidiu')])),
                ('catering_options', models.CharField(choices=[('Bucatarie proprie', 'Bucatarie proprie'), ('Servicii de catering incluse sau opționale', 'Servicii de catering incluse sau opționale'), ('Meniuri speciale', 'Meniuri speciale'), ('Degustare meniu', 'Degustare meniu'), ('Serviciul ospatarilor gratuit', 'Serviciul ospatarilor gratuit'), ('Candy Bar', 'Candy Bar'), ('Shot Bar', 'Shot Bar'), ('Fruit Bar', 'Fruit Bar'), ('Cocktail Bar', 'Cocktail Bar')])),
                ('parking_options', models.CharField(choices=[('Parcare gratuita', 'Parcare gratuita'), ('Parcare platita', 'Parcare platita')])),
            ],
        ),
    ]
