# Generated by Django 5.0.6 on 2024-10-10 08:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallRoom',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('maximum_guests_number', models.IntegerField()),
                ('event_facilities_selection', multiselectfield.db.fields.MultiSelectField(choices=[('Decoratiuni incluse', 'Decoratiuni incluse'), ('Decor mese', 'Decor mese'), ('Decor scaune', 'Decor scaune'), ('Meniuri pentru mese', 'Meniuri pentru mese'), ('Casuta de dar', 'Casuta de dar'), ('Event planner', 'Event planner'), ('Stativ cu lista invitatilor', 'Stativ cu lista invitatilor'), ('Numere pentru mese', 'Numere pentru mese'), ('Obiceiuri', 'Obiceiuri'), ('Masina de fum', 'Masina de fum'), ('Gheata Carbonica', 'Gheata Carbonica'), ('Efecte pirotehnice', 'Efecte pirotehnice')], default='', max_length=198)),
                ('location_facilities', multiselectfield.db.fields.MultiSelectField(choices=[('Aer Conditionat', 'Aer Conditionat'), ('Sistem de sonorizare', 'Sistem de sonorizare'), ('Lumini arhitecturale', 'Lumini arhitecturale'), ('Iluminat profesional', 'Iluminat profesional'), ('Ring de dans', 'Ring de dans'), ('Scenă pentru formație/muzicieni', 'Scenă pentru formație/muzicieni'), ('Baie Separata', 'Baie Separata'), ('Prezidiu', 'Prezidiu'), ('Wifi', 'Wifi'), ('Proximitea centrului orasului', 'Proximitatea centrului orasului'), ('Foto corner', 'Foto corner'), ('Loc de relaxare', 'Loc de relaxare '), ('Grup sanitar persoane cu dizabilitati', 'Grup sanitar persoane cu dizabilitati')], default='', max_length=247)),
                ('catering_options', multiselectfield.db.fields.MultiSelectField(choices=[('Meniu Personalizat', 'Meniu Personalizat'), ('Bucatarie proprie', 'Bucatarie proprie'), ('Servicii de catering incluse sau opționale', 'Servicii de catering incluse sau opționale'), ('Meniuri speciale', 'Meniuri speciale'), ('Degustare meniu', 'Degustare meniu'), ('Serviciul ospatarilor gratuit', 'Serviciul ospatarilor gratuit'), ('Candy Bar', 'Candy Bar'), ('Shot Bar', 'Shot Bar'), ('Fruit Bar', 'Fruit Bar'), ('Cocktail Bar', 'Cocktail Bar'), ('Open bar', 'Open bar'), ('All inclusive', 'All inclusive'), ('Cofetarie/Patiserie', 'Cofetarie/Patiserie')], default='', max_length=227)),
                ('parking_options', multiselectfield.db.fields.MultiSelectField(choices=[('Parcare gratuita', 'Parcare gratuita'), ('Parcare privata', 'Parcare privata'), ('Supreaveghere video', 'Supraveghere video'), ('Parcare iluminata', 'Parcare iluminata'), ('Parcare interioara', 'Parcare interioara'), ('Drum asfaltat', 'Drum asfaltat')], default='', max_length=103)),
                ('zona_exterioara_options', multiselectfield.db.fields.MultiSelectField(choices=[('Loc pentru fumat', 'Loc pentru fumat'), ('Terasa acoperita', 'Terasa acoperita'), ('Terasa descoperita', 'Terasa descoperita'), ('Piscina', 'Piscina'), ('Foisor evenimente', 'Foisor evenimente'), ('Zona foto', 'Zona foto'), ('Fantana arteziana', 'Fantana arteziana'), ('Loc de joaca', 'Loc de joaca'), ('Gradina amenajata pentru ceremonie', 'Gradina amenajata pentru ceremonie'), ('Locatie pe lac', 'Locatie pe lac'), ('Vedere la lac', 'Vedere la lac'), ('Locatie in padure', 'Locatie in padure'), ('Vedere panoramica', 'Vedere panoramica')], default='', max_length=219)),
                ('siguranta_options', multiselectfield.db.fields.MultiSelectField(choices=[('Alarma incendiu', 'Alarma incendiu'), ('Detectoare de fum', 'Detectoare de fum'), ('Acces ambulanta', 'Acces ambulanta'), ('Supreaveghere video', 'Supraveghere video'), ('Extinctoare', 'Extinctoare'), ('Serviciu de paza', 'Serviciu de paza'), ('Kit de prim ajutor', 'Kit de priim ajutor')], default='', max_length=117)),
                ('minim_menu_price', models.IntegerField(blank=True)),
                ('meniu', models.FileField(upload_to='pdf-menus')),
            ],
            bases=('MainApp.clientdetails',),
        ),
    ]
