# Generated by Django 5.0.6 on 2024-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballroom',
            name='adress',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ballroom',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'Bucuresti'), ('Cluj', 'Cluj'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta'), ('Timis', 'Timis'), ('Brasov', 'Brasov'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Bihor', 'Bihor'), ('Prahova', 'Prahova'), ('Braila', 'Braila'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Sibiu', 'Sibiu'), ('Mures', 'Mures'), ('Maramures', 'Maramures'), ('Buzau', 'Buzau'), ('Valcea', 'Valcea'), ('Satu Mare', 'Satu Mare'), ('Botosani', 'Botosani'), ('Suceava', 'Suceava'), ('Caras-Severin', 'Caras-Severin'), ('Mehedinti', 'Mehedinti'), ('Neamt', 'Neamt'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Gorj', 'Gorj'), ('Dambovita', 'Dambovita'), ('Vrancea', 'Vrancea'), ('Tulcea', 'Tulcea'), ('Alba', 'Alba'), ('Olt', 'Olt'), ('Vaslui', 'Vaslui'), ('Calarasi', 'Calarasi'), ('Giurgiu', 'Giurgiu'), ('Ilfov', 'Ilfov'), ('Hunedoara', 'Hunedoara'), ('Salaj', 'Salaj'), ('Covasna', 'Covasna'), ('Harghita', 'Harghita'), ('Ialomita', 'Ialomita'), ('Teleorman', 'Teleorman')], default='Bucuresti'),
        ),
        migrations.AddField(
            model_name='ballroom',
            name='siguranta_options',
            field=models.CharField(choices=[('Alarma incendiu', 'Alarma incendiu'), ('Detectoare de fum', 'Detectoare de fum'), ('Acces ambulanta', 'Acces ambulanta'), ('Supreaveghere video', 'Supraveghere video'), ('Extinctoare', 'Extinctoare'), ('Serviciu de paza', 'Serviciu de paza'), ('Kit de prim ajutor', 'Kit de priim ajutor')], default=''),
        ),
        migrations.AddField(
            model_name='ballroom',
            name='zona_exterioara_options',
            field=models.CharField(choices=[('Loc pentru fumat', 'Loc pentru fumat'), ('Terasa acoperita', 'Terasa acoperita'), ('Terasa descoperita', 'Terasa descoperita'), ('Piscina', 'Piscina'), ('Foisor evenimente', 'Foisor evenimente'), ('Zona foto', 'Zona foto'), ('Fantana arteziana', 'Fantana arteziana'), ('Loc de joaca', 'Loc de joaca'), ('Gradina amenajata pentru cereemonie', 'Gradina amenajata pentru ceremonie')], default=''),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='catering_options',
            field=models.CharField(choices=[('Bucatarie proprie', 'Bucatarie proprie'), ('Servicii de catering incluse sau opționale', 'Servicii de catering incluse sau opționale'), ('Meniuri speciale', 'Meniuri speciale'), ('Degustare meniu', 'Degustare meniu'), ('Serviciul ospatarilor gratuit', 'Serviciul ospatarilor gratuit'), ('Candy Bar', 'Candy Bar'), ('Shot Bar', 'Shot Bar'), ('Fruit Bar', 'Fruit Bar'), ('Cocktail Bar', 'Cocktail Bar'), ('Obiceiuri', 'Obiceiuri'), ('Open bar', 'Open bar'), ('All inclusive', 'All inclusive'), ('Cofetarie/Patiserie', 'Cofetarie/Patiserie '), ('Drum asfaltat', 'Drum asfaltat')], default=''),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='location_facilities',
            field=models.CharField(choices=[('Aer Conditionat', 'Aer Conditionat'), ('Sistem de sonorizare', 'Sistem de sonorizare'), ('Lumini arhitecturale', 'Lumini arhitecturale'), ('Iluminat profesional', 'Iluminat profesional'), ('Ring de dans', 'Ring de dans'), ('Scenă pentru formație/muzicieni', 'Scenă pentru formație/muzicieni'), ('Decoratiuni incluse', 'Decoratiuni incluse'), ('Baie Separata', 'Baie Separata'), ('Prezidiu', 'Prezidiu'), ('Decor mese', 'Decor mese'), ('Wifi', 'Wifi'), ('Decor scaune', 'Decor scaune'), ('Meniuri pentru meese', 'Meniuri pentru mese'), ('Vedere panoramica', 'Vedere panoramica'), ('Proximitea centrului orasului', 'Proximitatea centrului orasului'), ('Foto corner', 'Foto corner'), ('Casuta de dar', 'Casuta de dar'), ('Locatie pe lac', 'Locatie pe lac'), ('Vedere la lac', 'Vedere la lac'), ('Locatie in padure', 'Locatie in padure'), ('Event planner', 'Event planner'), ('Stativ cu lista invitatilor', 'Stativ cu lista invitatilor'), ('Numere pentru mese', 'Numere pentru mese'), ('Loc de relaxare', 'Loc de relaxare ')], default=''),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='parking_options',
            field=models.CharField(choices=[('Parcare gratuita', 'Parcare gratuita'), ('Parcare platita', 'Parcare platita'), ('Supreaveghere video', 'Supraveghere video'), ('Parcare iluminata', 'Parcare iluminata')], default=''),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='type_of_events',
            field=models.CharField(choices=[('NUNTA', 'Nunta'), ('BOTEZ', 'Botez'), ('CORPORATE', 'Corporate'), ('ALTELE', 'Altele')], default=''),
        ),
    ]
