# Generated by Django 5.0.6 on 2024-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0002_ballroom_adress_ballroom_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballroom',
            name='county',
            field=models.CharField(choices=[('Bucuresti', 'Bucuresti'), ('Cluj', 'Cluj'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta'), ('Timis', 'Timis'), ('Brasov', 'Brasov'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Bihor', 'Bihor'), ('Prahova', 'Prahova'), ('Braila', 'Braila'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Sibiu', 'Sibiu'), ('Mures', 'Mures'), ('Maramures', 'Maramures'), ('Buzau', 'Buzau'), ('Valcea', 'Valcea'), ('Satu Mare', 'Satu Mare'), ('Botosani', 'Botosani'), ('Suceava', 'Suceava'), ('Caras-Severin', 'Caras-Severin'), ('Mehedinti', 'Mehedinti'), ('Neamt', 'Neamt'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Gorj', 'Gorj'), ('Dambovita', 'Dambovita'), ('Vrancea', 'Vrancea'), ('Tulcea', 'Tulcea'), ('Alba', 'Alba'), ('Olt', 'Olt'), ('Vaslui', 'Vaslui'), ('Calarasi', 'Calarasi'), ('Giurgiu', 'Giurgiu'), ('Ilfov', 'Ilfov'), ('Hunedoara', 'Hunedoara'), ('Salaj', 'Salaj'), ('Covasna', 'Covasna'), ('Harghita', 'Harghita'), ('Ialomita', 'Ialomita'), ('Teleorman', 'Teleorman')], default='Bucuresti'),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='city',
            field=models.CharField(choices=[('Bucuresti', 'Bucuresti')], default='Bucuresti', max_length=255),
        ),
        migrations.AlterField(
            model_name='ballroom',
            name='minimum_guests_number',
            field=models.IntegerField(),
        ),
    ]
