# Generated by Django 5.0.6 on 2024-07-28 16:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0003_ballroom_county_alter_ballroom_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('Salon', 'Salon'), ('Coafor', 'Coafor'), ('Catering', 'Catering'), ('Fotograf', 'Fotograf'), ('Valet', 'Valet')], default='', max_length=255)),
                ('county', models.CharField(choices=[('Bucuresti', 'Bucuresti'), ('Cluj', 'Cluj'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta'), ('Timis', 'Timis'), ('Brasov', 'Brasov'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Bihor', 'Bihor'), ('Prahova', 'Prahova'), ('Braila', 'Braila'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Sibiu', 'Sibiu'), ('Mures', 'Mures'), ('Maramures', 'Maramures'), ('Buzau', 'Buzau'), ('Valcea', 'Valcea'), ('Satu Mare', 'Satu Mare'), ('Botosani', 'Botosani'), ('Suceava', 'Suceava'), ('Caras-Severin', 'Caras-Severin'), ('Mehedinti', 'Mehedinti'), ('Neamt', 'Neamt'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Gorj', 'Gorj'), ('Dambovita', 'Dambovita'), ('Vrancea', 'Vrancea'), ('Tulcea', 'Tulcea'), ('Alba', 'Alba'), ('Olt', 'Olt'), ('Vaslui', 'Vaslui'), ('Calarasi', 'Calarasi'), ('Giurgiu', 'Giurgiu'), ('Ilfov', 'Ilfov'), ('Hunedoara', 'Hunedoara'), ('Salaj', 'Salaj'), ('Covasna', 'Covasna'), ('Harghita', 'Harghita'), ('Ialomita', 'Ialomita'), ('Teleorman', 'Teleorman')], default='Bucuresti')),
                ('city', models.CharField(choices=[('Bucuresti', 'Bucuresti')], default='Bucuresti', max_length=255)),
                ('adress', models.CharField(default='', max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('contact_email', models.EmailField(max_length=254)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anunt',
            },
        ),
    ]
