# Generated by Django 5.0.6 on 2024-07-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0005_attributesalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesalon',
            name='catering',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributesalon',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributesalon',
            name='parking',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributesalon',
            name='saftey',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributesalon',
            name='type_events',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='attributesalon',
            name='zona_exterior',
            field=models.TextField(blank=True),
        ),
    ]
