# Generated by Django 5.0.6 on 2024-08-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0006_alter_attributesalon_catering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesalon',
            name='descriere',
            field=models.TextField(blank=True),
        ),
    ]
