# Generated by Django 5.0.6 on 2024-08-11 14:26

import Saloane.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saloane', '0007_alter_attributesalon_descriere'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCatering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anunt', models.IntegerField()),
                ('descriere', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('Corporate', 'Corporate'), ('Private', 'Private'), ('Nunta', 'Nunta'), ('Botez', 'Botez')], default='', max_length=255)),
                ('image', models.FileField(blank=True, upload_to=Saloane.models.UploadToDirectory())),
            ],
            options={
                'db_table': 'attribute_catering',
            },
        ),
        migrations.CreateModel(
            name='AttributeCoafor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anunt', models.IntegerField()),
                ('descriere', models.TextField(blank=True)),
                ('type', models.CharField(default='', max_length=255)),
                ('image', models.FileField(blank=True, upload_to=Saloane.models.UploadToDirectory())),
            ],
            options={
                'db_table': 'attribute_coafor',
            },
        ),
        migrations.CreateModel(
            name='AttributeFotograf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anunt', models.IntegerField()),
                ('descriere', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to=Saloane.models.UploadToDirectory())),
            ],
            options={
                'db_table': 'attribute_fotograf',
            },
        ),
        migrations.CreateModel(
            name='AttributeValet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_anunt', models.IntegerField()),
                ('descriere', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attribute_valet',
            },
        ),
        migrations.AddField(
            model_name='ballroom',
            name='descriere',
            field=models.TextField(default='Descriere'),
        ),
        migrations.AlterField(
            model_name='anunt',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
