# Generated by Django 5.0.6 on 2024-10-10 08:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVideo',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('servicii_fotovideo', multiselectfield.db.fields.MultiSelectField(choices=[('Fotografie', 'Fotografie'), ('Video', 'Video'), ('Cabina Foto', 'Cabina Foto'), ('Cabina 360', 'Cabina 360')], default='', max_length=39)),
                ('facilities_selection', multiselectfield.db.fields.MultiSelectField(choices=[('Multipli operatori', 'Multipli operatori'), ('Albume', 'Albume'), ('Drona', 'Drona'), ('Macara', 'Macara'), ('Slide', 'Slide'), ('Steady', 'Steady')], default='', max_length=51)),
            ],
            bases=('MainApp.clientdetails',),
        ),
    ]
