# Generated by Django 5.0.6 on 2024-10-10 08:15

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpSaloon',
            fields=[
                ('clientdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MainApp.clientdetails')),
                ('servicii_select', multiselectfield.db.fields.MultiSelectField(choices=[('Hair Saloon', 'Hair Saloon'), ('Make Up', 'Make Up')], default='', max_length=19)),
                ('servicies_field', multiselectfield.db.fields.MultiSelectField(choices=[('Accesorii Par', 'Accesorii Par'), ('Bronzare', 'Bronzare'), ('Extensii Par', 'Extensii Par'), ('Extensii Gene', 'Extensii Gene'), ('Manichiura / Pedichiura', 'Manichiura / Pedichiura'), ('Frizerie / Barber Shop', 'Frizerie / Barber Shop'), ('Coafor', 'Coafor'), ('Epilare', 'Epilare')], default='', max_length=111)),
                ('locatie_desfasurare', multiselectfield.db.fields.MultiSelectField(choices=[('Salon', 'Salon'), ('La domiciliu clientului', 'La domiciliu clientului')], default='', max_length=29)),
            ],
            bases=('MainApp.clientdetails',),
        ),
    ]
